version: '3'
services:
  cve_search_app:
    build: .
    image: cve_search:v1
    links:
      - cve_search_mongo
      - cve_search_redis
    ports:
      - 5000:5000
    environment:
       - SEARCHCVE_MONGOHOST=cve_search_mongo
       - SEARCHCVE_REDISHOST=cve_search_redis
       - SEARCHCVE_CVESTARTYEAR=2018

  cve_search_mongo:
    image: mongo:latest
    expose:
      - 27017
  cve_search_redis:
    image: redis:latest
    expose:
      - 6379
