version: '3'
services:
  cve_search_app:
    build: .
    image: cve_search:v1
    links:
      - cve_search_mongo
      - cve_search_redis
    ports:
      - 5000:5000
    environment:
       - SEARCHCVE_MONGOHOST=cve_search_mongo
       - SEARCHCVE_REDISHOST=cve_search_redis
       - SEARCHCVE_CVESTARTYEAR=2018
       - SEARCHCVE_FLASKHOST=0.0.0.0
       - SEARCHCVE_LOGINREQUIRED=True
       - SEARCHCVE_DEFAULTUSER=Admin1
       #Change me, escape with  $$
       - SEARCHCVE_DEFAULTUSERPWD=$$pbkdf2-sha256$$8000$$WKv1/l.LkXKOkQ$$6/cX4QE8/WqRZLafOdO4XM7Vwf2ERuM.lhxr8vAdOSI

  cve_search_mongo:
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - ../data/mongo:/data/db
  cve_search_redis:
    image: redis:latest
    expose:
      - 6379
