apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: devsecops-ivv
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /data/db
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mongo-pv-claim
    namespace: devsecops-ivv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: devsecops-ivv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
